language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.5"
sudo: required

services:
  - postgresql

before_script:
  - psql --command 'CREATE USER admin WITH SUPERUSER PASSWORD '123456789';'
  - psql -c 'create database hexandriaTest' -U postgres

install:
  - mvn clean install