language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.5"
sudo: required

services:
  - postgresql

before_install:
  - psql --command "CREATE USER admin WITH SUPERUSER PASSWORD '123456789';"
  - psql -c 'CREATE DATABASE hexandria-test WITH OWNER admin;'

install:
  - mvn clean install